feat: implement paging API
kookmin-sw/capstone-2023-40 pull request #115
Opened 2023-04-20 19:31 UTC by kimjinmyeong

**Added**
- The paging has been applied to the `getAllSurvey` method in `SurveyController`
- Implemented validate invalid request to paging API in `SurveyService`
- Added `com/thesurvey/api/dto/response/SurveyListPageDto.java` to response 
- Added `com/thesurvey/api/dto/request/CustomPageable.java`to custom "모든 설문조사 조회" page in swagger
- Added test code to paging

Clients cannot manipulate the page `size` and `sort` in the request and `size` is fixed at **8**.
Clients can request the server as follows: 
`/v1/surveys?page=0`

<details> 
<summary> response paging API example </summary>
<pre> 
{
    "content": [ // The data included in the current page
        {
            "surveyId": "cd21679c-bb69-46e4-8453-528516452d0c",
            "authorId": 1,
            "title": "Sample Survey",
            "description": "A simple survey",
            "startedDate": "2023-04-21T14:25:00",
            "endedDate": "2023-04-27T23:59:59",
            "modifiedDate": "2023-04-21T04:03:45.163133",
            "certificationTypes": [
                "KAKAO",
                "NAVER"
            ]
        }
    ],
    "pageable": { // Information about the page
        "sort": {
            "empty": true,
            "unsorted": true,
            "sorted": false
        },
        "offset": 0, // indicates the starting position of the current page
        "pageNumber": 0,
        "pageSize": 8,
        "paged": true,
        "unpaged": false
    },
    "last": true, // Indicates whether the current page is the last page.
    "totalElements": 1, // The total number of pages.
    "totalPages": 1, // The total number of pages.
    "number": 0, // The current page number.
    "sort": {
        "empty": true,
        "unsorted": true,
        "sorted": false
    },
    "first": true, // Indicates whether the current page is the first page.
    "size": 8, // The page size.
    "numberOfElements": 1,
    "empty": false
}
</pre>
</details>

This PR closes #79

2023-04-21 06:01 UTC, SeiwonPark commented
_(Did I implement pagination or paging..??, Which term is correct??)_ -> Pagination is correct See [this](https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading?hl=ko)

2023-04-21 06:04 UTC, SeiwonPark commented
```
 
{
    "content": [ // The data included in the current page
        {
            "surveyId": "cd21679c-bb69-46e4-8453-528516452d0c",
            "authorId": 1,
            "title": "Sample Survey",
            "description": "A simple survey",
            "startedDate": "2023-04-21T14:25:00",
            "endedDate": "2023-04-27T23:59:59",
            "modifiedDate": "2023-04-21T04:03:45.163133",
            "certificationTypes": [
                "KAKAO",
                "NAVER"
            ]
        }
    ],
    "pageable": { // Information about the page
        "sort": {
            "empty": true,
            "unsorted": true,
            "sorted": false
        },
        "offset": 0, // indicates the starting position of the current page
        "pageNumber": 0,
        "pageSize": 8,
        "paged": true,
        "unpaged": false
    },
    "last": true, // Indicates whether the current page is the last page.
    "totalElements": 1, // The total number of pages.
    "totalPages": 1, // The total number of pages.
    "number": 0, // The current page number.
    "sort": {
        "empty": true,
        "unsorted": true,
        "sorted": false
    },
    "first": true, // Indicates whether the current page is the first page.
    "size": 8, // The page size.
    "numberOfElements": 1,
    "empty": false
}
```

I see too much duplicated values. Could you cut off some? IDK why values like `"first": true,` is needed.

2023-04-21 06:08 UTC, bezzang-dev commented
I will add a response DTO to modify the API's response and include only the necessary information.

2023-04-21 06:19 UTC, seiwonpark requested changes
Please update your code and re-request.

2023-04-21 06:19 UTC, seiwonpark commented on api/src/main/java/com/thesurvey/api/controller/SurveyController.java
> +    public ResponseEntity<Page<SurveyListPageDto>> getAllSurvey(@PageableDefault(page = 0, size = 8) Pageable pageable) {
**!!!**

![array](https://user-images.githubusercontent.com/63793178/233553505-9f08ecf1-52c6-42b4-88c7-f39c09063d7b.png)

2023-04-21 06:19 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/controller/SurveyController.java
> +    public ResponseEntity<Page<SurveyListPageDto>> getAllSurvey(@PageableDefault(page = 0, size = 8) Pageable pageable) {
How about setting entry page to 1?

2023-04-21 06:19 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/dto/request/CustomPageable.java
> +    @ApiModelProperty(name = "페이지 수", example = "가져올 페이지의 번호를 나타냅니다.", notes = "0 부터 시작하며, 유효하지 않은 값은 0으로 설정됩니다.")
`example` should be the actual value. This is not description

2023-04-21 06:19 UTC, seiwonpark commented on api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
> +    INVALID_PAGE_SIZE("페이지 크기는 8 이어야 합니다."),
Why would client need to know `pageSize`? This should be fixed value. `PAGE_NOT_FOUND` should be enough

2023-04-21 06:19 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
> +    INVALID_PAGE_SORT("페이지 정렬은 기본 값이어야 합니다."),
Same above. Client should not be able to set anything for pagination except request parameter `page` which indicates actual page number. Seems like this error message is for some client request that could change the method of sorting policy

2023-04-21 06:19 UTC, SeiwonPark commented on api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
> +                .param("page", "1")
![array](https://user-images.githubusercontent.com/63793178/233555489-6e36a967-ebd2-4670-a5ad-4110704dcdac.png)

2023-04-21 06:19 UTC, SeiwonPark commented on api/src/test/java/com/thesurvey/api/controller/SurveyControllerTest.java
> +                .param("page", "1")
And this starts from `1`!

2023-04-21 06:19 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/exception/ErrorMessage.java
> +    INVALID_PAGE_SORT("페이지 정렬은 기본 값이어야 합니다."),
Oh okay this is  for **filtering** option. Resolved.

2023-04-22 00:46 UTC, SeiwonPark approved these changes
LGTM. Thanks!

2023-04-22 03:13 UTC, merged