feat: 설문조사 참여, 설문조사 리스트 페이지 api 연결 및 리팩토링
kookmin-sw/capstone-2023-40 pull request #143
Opened 2023-05-09 06:21 UTC by sanghyun1128

설문조사 참여 페이지 api 연결

- GET /surveys/{surveyId} 

- POST /surveys/submit

설문조사 리스트 페이지 api 연결

- GET /surveys?page={page}

리팩토링
- 모여있던 코드 분리
- Date 포맷팅해서 보여주는 유틸 함수 추가
- 버튼 컴포넌트 추가

Closes #142

2023-05-09 07:29 UTC, ohsung1125 approved these changes
LGTM!

2023-05-10 06:10 UTC, SeiwonPark requested changes
Please update your code and re-request.

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      }
This could be refactored like follows:

```typescript
const setAlertNotificationStyle = (errorIndex: number) => {
  surveyData.questions.forEach((question: QuestionCreateRequest, index: number) => {
    const questionNumber = question.questionNo - 1;
    const borderStyle = questionNumber === errorIndex ? '15px solid #FF5733' : `15px solid ${theme.colors.primary}`;
    questionRefs.current[index].style.borderLeft = borderStyle;
  });
};
```

(I've not tested this)

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +  });
These states could be refactored with reducer. Currently okay.

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/CertificationList.tsx
> +  // FIXME: CertificationType allow both number and string... it makes happen with switch function
Could you explain about this? Which type does response come in then?

2023-05-10 06:10 UTC, seiwonpark commented on web/src/api/axios.ts
> +instance.defaults.withCredentials = true;
I'm not sure but is it okay to put `withCredentials` as create option?

I mean, like below
```typescript
const instance: AxiosInstance = axios.create({
  ...,
  withCredentials: true
});
```
Because we could set some options like `timeout` inside create method and this could be more handy I guess.

2023-05-10 06:10 UTC, seiwonpark commented on docker-compose.yml
> +  #     - 3000:3000
Isn't this required?

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +    if (typeof questionId !== 'undefined') {
```typescript
if (typeof questionId === 'undefined') return;

if (name === 'addQuestion') addQuestionUnderId(questionId);
else if (name === 'deleteQuestion') deleteQuestionAtId(questionId);
else if (name === 'addOption') addOptionAtBottom(questionId);
else if (typeof optionId !== 'undefined') deleteOptionAtId(questionId, optionId);
```

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +    }
This would be more neat.

```typescript
newOptions = newOptions ? [...newOptions, newOption] : [newOption];
```

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +  };
Likewise please refactor this method

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      {surveyData.questions.map((question: QuestionCreateRequest) => (
I've got a question here which is better, `map()` or `forEach()`.

- [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map): creates a new array
- [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach): do some operation within that exact array

Without second thought, I guess `forEach()` would be better choice but what is your idea?

2023-05-10 06:10 UTC, seiwonpark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      {resultModalOpen && <SurveyPageResultModal theme={theme} />}
I'd like to ask you if you could answer this question.

Q. Why is it okay to use `&&` operator on this line and when do we have to avoid this?

2023-05-10 06:10 UTC, SeiwonPark commented on web/src/components/SurveyListTable.tsx
> +            <AuthList theme={theme}>
Could you separate this `<AuthList>` component? This is the same reason for your separated component of `<Pagination>`

2023-05-10 06:10 UTC, SeiwonPark commented on web/src/components/SurveyParticipateForm/ResponseInputForm.tsx
> +}
What is the intend to check single choice and multiple choices with `if statement` and short answer and long answer with `switch statement`?

2023-05-10 06:10 UTC, SeiwonPark commented on web/src/utils/dateFormat.ts
> + * @param {string | Date} dDate yyyy-mm-ddThh:MM:ss.zzzZ
typo here

2023-05-10 06:10 UTC, SeiwonPark commented on web/src/utils/dateFormat.ts
> + * @param {string} date yyyy-mm-ddThh:MM:ss.zzzZ
Is it `yyyy-mm-ddThh:MM:ss.zzzZ`?  Isn't it `yyyy-mm-ddThh:MM:ss.SSS`?

2023-05-10 06:10 UTC, SeiwonPark commented on web/src/utils/dateFormat.ts
> + * Replace T and remove milliseconds
This doesn't fully describe the util function. Add some information like `from datetime format` at the end.

2023-05-10 06:10 UTC, SeiwonPark requested changes
Please update your code and re-request.

2023-05-10 06:55 UTC, SeiwonPark commented on docker-compose.yml
> +  #     - 3000:3000
Checked. (use local web server)

2023-05-11 12:26 UTC, sanghyun1128 commented on web/src/components/SurveyParticipateForm/ResponseInputForm.tsx
> +}
주관식 같은 경우에 겹치는 코드가 있어서 따로 빼려 했는데, 생각해보니 그냥 switch로 통일하고 주관식 컴포넌트를 하나 더 만드는게 더 좋겠네요

2023-05-11 12:31 UTC, sanghyun1128 commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      {resultModalOpen && <SurveyPageResultModal theme={theme} />}
&&가 앞에게 false면 뒤에는 체크 안하고 넘겨서 이런식으로 쓰는걸로 알고있습니다. 
언제 피해야 할지는 확실하게 생각나는게 없네요....

2023-05-11 12:39 UTC, sanghyun1128 commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      {surveyData.questions.map((question: QuestionCreateRequest) => (
처음에 map() 쓰다가 익숙해져서 forEach() 써볼 생각을 못했습니다... 
map() 사용한 이유가 배열 생성하려는게 아니라 for문 대신으로 쓴건데 그런 용도면 forEach()가 더 좋겠네요 변경하겠습니다.

2023-05-11 12:40 UTC, seiwonpark commented on web/src/components/SurveyParticipateForm/ResponseInputForm.tsx
> +}
Keeping components consistent will make the code more maintainable.

2023-05-11 12:40 UTC, sanghyun1128 commented on web/src/api/axios.ts
> +instance.defaults.withCredentials = true;
네 create 안에 넣어도 되고 잘 작동합니다. 수정하겠습니다.

2023-05-11 12:41 UTC, SeiwonPark commented on web/src/api/axios.ts
> +instance.defaults.withCredentials = true;
That would be more neat. Thank you!

2023-05-11 12:53 UTC, sanghyun1128 commented on web/src/components/CertificationList.tsx
> +  // FIXME: CertificationType allow both number and string... it makes happen with switch function
제가 enum을 잘 몰라서 문제가 발생했는데(아직도 햇갈려요)
label: `CertificationType` 으로 타입을 지정해 두면 사용할때 `0` 이나 `'KAKAO'` 둘다 들어 갔었습니다. 
그렇다고 `0`을 `CertificationType[0]` 이런식으로 넣으려고 하면 `CertificationType` 이 아니라고 안됬습니다.
이렇게 들어왔을 때 문제가 `'KAKAO'` 가 들어오면 
`case CertificationType.KAKAO:` 에서 안걸리고 default로 실행되서 
`tmpLabel` 변수 만들어서 타입을 통일하는 과정을 추가했습니다.

이렇게 하는게 적절한 방법인지 모르겠어서 주석 달아 놨었습니다.

2023-05-11 12:57 UTC, sanghyun1128 commented on web/src/utils/dateFormat.ts
> + * @param {string} date yyyy-mm-ddThh:MM:ss.zzzZ
swagger 문서에 `"endedDate": "2023-05-11T12:56:36.690Z", ` 이런식으로 되있던데 `SSS`로 변경되었나요?

2023-05-11 15:18 UTC, sanghyun1128 commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +    if (typeof questionId !== 'undefined') {
이렇게 고치면 밑에 `questionId`에 오류가 생깁니다.

2023-05-11 15:40 UTC, kimjinmyeong commented on web/src/utils/dateFormat.ts
> + * @param {string} date yyyy-mm-ddThh:MM:ss.zzzZ
> swagger 문서에 `"endedDate": "2023-05-11T12:56:36.690Z", ` 이런식으로 되있던데 `SSS`로 변경되었나요?

현재 설문조사 응답 시 사용하는 `SurveyResponseDto`에서 `endedDate`의 대한 Json Format이
`yyyy-MM-dd'T'HH:mm:ss`로 수정되어있긴 합니다.

예시 JSON 데이터 입니다
```
    "description": "A simple survey",
    "startedDate": "2023-05-11T20:46:00",
    "endedDate": "2023-05-30T19:42:00",
```

.SSS는 잘 모르겠습니다..

2023-05-11 16:14 UTC, sanghyun1128 commented on web/src/utils/dateFormat.ts
> + * @param {string | Date} dDate yyyy-mm-ddThh:MM:ss.zzzZ
어디 말씀하시는 걸까요?

2023-05-12 02:04 UTC, SeiwonPark commented on web/src/components/CertificationList.tsx
> +  // FIXME: CertificationType allow both number and string... it makes happen with switch function
`label: CertificationType`은 파라미터의 타입을 강제하는 역할을 하지 않습니다. `number`이든, `string`이든 일단 모두 다 받습니다. 파라미터의 타입을 강제하기 위해선 별도의 로직(ex. [ajv](https://ajv.js.org/))이 필요합니다.

TypeScript는 컴파일 시 타입을 강제하는 역할을 하는 언어이지, 런타임 시의 동작을 보장하지는 않습니다. 서버로부터의 응답이 `KAKAO`(string)로 오는지 `0`(number)로 오는지 확인한 다음, 그에 맞게 처리하시면 됩니다.

2023-05-12 02:14 UTC, SeiwonPark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +    if (typeof questionId !== 'undefined') {
```typescript
if (typeof questionId === 'undefined') return;

if (name === 'addQuestion') addQuestionUnderId(questionId?);
else if (name === 'deleteQuestion') deleteQuestionAtId(questionId?);
else if (name === 'addOption') addOptionAtBottom(questionId?);
else if (typeof optionId !== 'undefined') deleteOptionAtId(questionId?, optionId);
```

how about now?

2023-05-12 02:18 UTC, SeiwonPark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      {resultModalOpen && <SurveyPageResultModal theme={theme} />}
`boolean` 값은 `&&`로 사용하셔도 됩니다. 그치만 Collection일 경우, 지양하시는 걸 권장드립니다. 빈 객체일 경우, `&&` 연산 통과 합니다. 알고계시면 좋을 것 같아 질문드렸습니다.

2023-05-12 02:54 UTC, SeiwonPark commented on web/src/utils/dateFormat.ts
> + * @param {string} date yyyy-mm-ddThh:MM:ss.zzzZ
1. 오타가 있네요. `yyyy-mm-ddThh:MM:ss.SSSZ`라고 했어야 했습니다. `yyyy-mm-ddThh:MM:ss.zzzZ`와 같은 형태는 본 적이 없어서 여쭤봤습니다.
2. Swagger에 이런 문제가 있군요. 진명님께서 공유해주신 형태로 처리하시면 됩니다. (실제 데이터가 요청/응답 시 전달되는 포멧입니다)

2023-05-12 07:00 UTC, sanghyun1128 commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      {surveyData.questions.map((question: QuestionCreateRequest) => (
`forEach()` 써봤는데 배열을 생성 안해서 React 컴포넌트를 리턴을 못해 주네요....`map()` 쓰는게 맞는거 같습니다

2023-05-12 07:14 UTC, SeiwonPark approved these changes
LGTM!

2023-05-12 07:14 UTC, seiwonpark commented on web/src/utils/dateFormat.ts
> + * @param {string | Date} dDate yyyy-mm-ddThh:MM:ss.zzzZ
위 리뷰 참고해 해당 라인 다시 수정부탁드립니다. `yyyy-mm-ddThh:MM:ss.zzzZ` 포멧이 아닙니다.

2023-05-12 07:14 UTC, seiwonpark commented on web/src/utils/dateFormat.ts
> +export const getDDay = (dDate: string | Date): number => {
`Return date difference between date1 and date2` 라고 설명이 돼 있는데, 이게 무슨 말인가요?

위 설명대로라면, 아래와 같은 형태여야 하지 않을까요?
```typescript
const foo = (date1: string | Date, date2: string | Date) => {}
```

그런데 파라미터를 하나만 받고 있고, 본인 외에는 누구도 알 수 없을 `dDate` 라는 변수를 사용하셨습니다. 이에 대한 설명도 없구요.

함수 전체와 주석 모두 수정해주세요.

추가)  `@returns {number} difference date` -> `@returns {number} date difference`

2023-05-12 07:14 UTC, seiwonpark commented on web/src/utils/dateFormat.ts
> + * @param {string} date yyyy-mm-ddThh:MM:ss.zzzZ
포멧은 `yyyy-MM-dd'T'HH:mm:ss`로 변경 부탁드립니다.

2023-05-12 07:14 UTC, seiwonpark commented on web/src/utils/dateFormat.ts
> + * @param {string} date yyyy-mm-ddThh:MM:ss.zzzZ
Same applies to this format

2023-05-12 07:14 UTC, SeiwonPark commented on web/src/components/SurveyCreateForm/SurveyCreateForm.tsx
> +      {surveyData.questions.map((question: QuestionCreateRequest) => (
굳굳

2023-05-12 07:14 UTC, SeiwonPark approved these changes
LGTM!

2023-05-12 07:33 UTC, merged