feat: 포인트 시스템 구현
kookmin-sw/capstone-2023-40 pull request #176
Opened 2023-05-20 13:17 UTC by kimjinmyeong

이 PR은 #175 이슈를 수행하였습니다.

**수행한 기능 구현**
- [X]  사용자가 보유한 포인트 조회
- [X]  질문 유형 별 필요한 포인트 차등 적용
- [X]  설문조사 생성 시 포인트 차감
- [X]  설문조사 생성 시 사용자가 필요한 포인트를 보유하고 있는지 검사
- [X]  설문조사 응답 제출 시 보상 포인트 획득
- [ ]  포인트를 사용하여 기프티콘 교환

**추가 사항**
- 사용자 회원가입 시 지급 포인트는 50 포인트 입니다.
- 설문조사 정보 조회 시 획득할 수 있는 포인트 정보를 포함합니다.
- 사용자 정보 조회 시 보유한 포인트 정보를 포함합니다.
- `EnumTypeEntity`에서 질문 유형과 설문조사 생성 및 제출 시 소모, 획득하는 포인트를 포함하는 `PointTransactionType`를 추가하였습니다.
- `isRequired`에 따라서 질문에 응답했는지 안했는지 검사 후 trim 을 적용하거나 포인트 획득량이 달라지도록 구현하였습니다.

**변경 사항**
- 설문조사 응답 제출 시 보상 포인트를 Response body에 포함하여 응답하도록 수정하였습니다.
- 설문조사 응답 요청 시 JSON 데이터에서  `isRequired`, `QuestionType`을 필요로 합니다.
```
{
  "surveyId": "bfb4ec42-34c2-43b3-9857-4d253ca9bae4",
  "answers": [
      {
          "questionBankId": 1,
          "isRequired" : true, // new
          "questionType" : "SINGLE_CHOICE", // new
          "singleChoice": 2
      }
  ]
}
```

**질문 유형 별 필요한 포인트**
- SINGLE_CHOICE: 2
- MULTIPLE_CHOICES: 4
- SHORT_ANSWER: 4
- LONG_ANSWER: 6

**질문 유형 별 획득 가능한 포인트**
- SINGLE_CHOICE: 1
- MULTIPLE_CHOICES: 2
- SHORT_ANSWER: :2 
- LONG_ANSWER: 3

2023-05-20 13:45 UTC, SeiwonPark requested changes
Please update your code and re-request.

2023-05-20 13:45 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
> +            if (answeredQuestionDto.getIsRequired() && validateEmptyAnswer(answeredQuestionDto)) {
@kimjinmyeong  만약 모든 설문 항목이 `필수(isRequired)`가 아닌 경우, empty answer는 요청이 되나요?

2023-05-20 13:45 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/dto/response/user/UserResponseDto.java
> +    private Integer userPoints;
Why not just `point`?

2023-05-20 13:45 UTC, SeiwonPark commented on api/src/test/java/com/thesurvey/api/service/PointHistoryServiceTest.java
> +                    .questionNo(1)
`questionNo` should be unique within question.

2023-05-20 14:01 UTC, kimjinmyeong commented on api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
> +            if (answeredQuestionDto.getIsRequired() && validateEmptyAnswer(answeredQuestionDto)) {
요청은 됩니다. 다만, 보상 포인트는 0 입니다.
만약 요청이 안되게 하려면 음... 당장은 떠오르는 아이디어는 없습니다..

2023-05-20 14:01 UTC, kimjinmyeong commented on api/src/main/java/com/thesurvey/api/dto/response/user/UserResponseDto.java
> +    private Integer userPoints;
세원님이 보내주신 [변수 명 짓기가 어려운 이유](https://www.youtube.com/watch?v=xXYQDzkydws) 을 보고 
좀 더 명확한 변수명을 짓기로 신경쓰다 보니 `userPoint`로 지었습니다.
포인트 관련 변수가 설문조사 보상 포인트, 설문조사 생성 포인트, 사용자가 보유한 포인트 가 있는데
사용자가 보유한 포인트라는 의미를 명확하게 해주고 싶어서 지었습니다
근데 `User` 정보를 응답하는 DTO 에서도 굳이 필요하나 싶긴 합니다. .
세원님 의견 듣고 수정토록 하겠습니다.

2023-05-20 14:04 UTC, kimjinmyeong commented on api/src/test/java/com/thesurvey/api/service/PointHistoryServiceTest.java
> +                    .questionNo(1)
수정하도록 하겠습니다.

2023-05-20 14:05 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/dto/response/user/UserResponseDto.java
> +    private Integer userPoints;
글쎄요.. 해당 컬럼이 하나만 존재할 뿐더러, 용도가 명확합니다. 말씀하신 이유시라면, `createdDate` 역시 `userCreatedDate`, `surveyCreatedDate`, `questionCreatedDate`로 모두 변경하시는게 일관되지 않나요?

2023-05-20 14:05 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
> +            if (answeredQuestionDto.getIsRequired() && validateEmptyAnswer(answeredQuestionDto)) {
요청 되면 안 됩니다.

2023-05-20 14:06 UTC, kimjinmyeong commented on api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
> +            if (answeredQuestionDto.getIsRequired() && validateEmptyAnswer(answeredQuestionDto)) {
모든 질문에 응답이 되지 않았을 때를 검사하는 로직을 추가해보도록 하겠습니다.

2023-05-20 14:08 UTC, SeiwonPark commented
추가로, 포인트 시스템이라는 기능을 약 500라인에 걸쳐 구현하셨는데, 관련된 테스트가 하나만 추가 됐습니다. 이러면 어떻게 리뷰를 드려야 할 지 잘 모르겠습니다. 그냥 믿고 LGTM 드릴까요?

2023-05-20 14:09 UTC, kimjinmyeong commented on api/src/main/java/com/thesurvey/api/dto/response/user/UserResponseDto.java
> +    private Integer userPoints;
말씀하신게 맞습니다. 

> 좀 더 명확한 변수명을 짓기로 신경쓰다 보니 

를 반영하려면 지금 구현된 클래스 명들부터 모두 고쳐야될 판인데
지금이라도 알았으니 이제부터라도 제대로 짓자는 생각입니다.

근데 컬럼이 하나만 존재하고 용도가 명확하다는 의견이 납득이 갑니다 `point` 로수정하도록 하겠습니다.

2023-05-20 14:10 UTC, kimjinmyeong commented
아닙니다 테스트 코드도 더 추가하도록 하겠습니다.

2023-05-20 14:10 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
> +            if (answeredQuestionDto.getIsRequired() && validateEmptyAnswer(answeredQuestionDto)) {
그냥 `validate`메서드의 반환타입을 `boolean`이 아닌 `void`로 다시 변경하시고, throw를 `validate`메서드 안에서 던지는게 가장 깔끔해보입니다. 구태여 `boolean`으로 해당 서비스 로직에서 체크해야 할 필요가 없어보입니다.

2023-05-20 14:13 UTC, SeiwonPark commented on api/src/main/java/com/thesurvey/api/dto/response/user/UserResponseDto.java
> +    private Integer userPoints;
참고로 `id`필드의 경우 의도적으로 `user_id`, `survey_id`로 구분했습니다. 보통은 그냥 `id`를 사용해서 쿼리에서 `user.id`를 사용하기 마련입니다. 하지만 개인적으로 id의 경우, 너무 많은 종류의 id(뿐만 아니라 `uuid`, 심지어는 ID_CARD의 `ID`)가 있어 이것만 구분하기 위해 사용했습니다.

2023-05-20 14:15 UTC, SeiwonPark commented
> 아닙니다 테스트 코드도 더 추가하도록 하겠습니다.

[이러한 상황](https://github.com/kookmin-sw/capstone-2023-40/pull/176#discussion_r1199613092)을 직접 머릿속으로 돌려보며 리뷰해야 하는 이유에서 드린 말씀이니 오해 없으시길 바랍니다.

2023-05-20 14:16 UTC, kimjinmyeong commented on api/src/main/java/com/thesurvey/api/dto/response/user/UserResponseDto.java
> +    private Integer userPoints;
설명 감사드립니다!

2023-05-20 16:27 UTC, kimjinmyeong commented on api/src/test/java/com/thesurvey/api/service/PointHistoryServiceTest.java
> +                    .questionNo(1)
`questionNo`가 사용자가 지정해서 오는게 아닌 서버에서 auto increment 해야한다고 하셨던게 기억이 나는데
그러면 설문조사 생성 및 수정 요청 DTO에서 `questionNo` 필드를 지워야 하는게 맞나요??

또한, 구현은 아래 처럼 `questionNo`라는 변수를 만들어서 질문마다 저장 후 1씩 증가하도록 하였습니다.
혹시 생각하신 의도가 이게 맞는지 여쭤보고 싶습니다.!
```
 @Transactional
    public void createQuestion(List<QuestionRequestDto> questionRequestDtoList, Survey survey) {
        int questionNo = 1;
        for (QuestionRequestDto questionRequestDto : questionRequestDtoList) {
            QuestionBank questionBank = questionBankRepository.save(
                questionBankMapper.toQuestionBank(questionRequestDto));

            questionRepository.save(questionMapper.toQuestion(questionRequestDto, survey,
                questionBank, questionNo++));
```

2023-05-21 06:24 UTC, kimjinmyeong commented on api/src/main/java/com/thesurvey/api/service/AnsweredQuestionService.java
> +            if (answeredQuestionDto.getIsRequired() && validateEmptyAnswer(answeredQuestionDto)) {
> validate메서드의 반환타입을 boolean이 아닌 void로 다시 변경하시고, throw를 validate메서드 안에서 던지는게 가장 깔끔해보입니다

말씀하신대로 `void`로 바꾸려 하였는데
필수 질문이 아닌 답변엔 throw를 일으킬 필요가 없고, 그런데 모든 질문에 답변을 안하면 throw를 일으켜야 하므로
어떤 식으로 구현해야할지 고민을 해보았습니다.

그래서 `validate` 메소드 타입을 `boolean`으로 하고
필수 질문인지 검사하는 조건에 같이 사용하여 다음과 같이 구현하였습니다

1. if (필수 질문인데 && `validateEmpty` 결과가 `true`이면) -> `throw exception`

2. if (`isAnswered`가 `false`인 상태인데 && `validateEmpty` 결과가 `false`이면) -> `isAnswer = true `

3. 모든 답변 순회 후 `isAnswer`가 `false`이면 모든 질문에 답변을 안함으로 판단


`validate` 메소드 리턴 타입을 `void`로 타입으로 사용하면서 모든 질문에 대해서 답변 등록을 안했는지 검사하는 다른 방법이 있을까요??

2023-05-21 14:40 UTC, SeiwonPark approved these changes
LGTM.

2023-05-21 16:18 UTC, merged